# Generated by Django 2.2 on 2021-05-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('realname', models.CharField(max_length=254, null=True)),
                ('password', models.CharField(max_length=18)),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('signature', models.TextField(null=True)),
                ('avatar', models.CharField(max_length=254, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('img', models.CharField(max_length=254)),
                ('type', models.IntegerField(choices=[(1, 'document'), (2, 'media'), (3, 'goods')])),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('is_remove', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.FloatField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_success', models.BooleanField(default=False)),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_record', to='front.User')),
                ('recipient_resources', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receive_record', to='front.Resources')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_record', to='front.User')),
                ('sender_resources', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='send_record', to='front.Resources')),
            ],
        ),
    ]
